// Code generated by Microsoft (R) TypeSpec Code Generator.

package tsptest.errormodel.implementation;

import io.clientcore.core.http.pipeline.HttpPipeline;

/**
 * Initializes a new instance of the ErrorModelClient type.
 */
public final class ErrorModelClientImpl {
    /**
     * Service host.
     */
    private final String endpoint;

    /**
     * Gets Service host.
     * 
     * @return the endpoint value.
     */
    public String getEndpoint() {
        return this.endpoint;
    }

    /**
     * The HTTP pipeline to send requests through.
     */
    private final HttpPipeline httpPipeline;

    /**
     * Gets The HTTP pipeline to send requests through.
     * 
     * @return the httpPipeline value.
     */
    public HttpPipeline getHttpPipeline() {
        return this.httpPipeline;
    }

    /**
     * The ErrorOpsImpl object to access its operations.
     */
    private final ErrorOpsImpl errorOps;

    /**
     * Gets the ErrorOpsImpl object to access its operations.
     * 
     * @return the ErrorOpsImpl object.
     */
    public ErrorOpsImpl getErrorOps() {
        return this.errorOps;
    }

    /**
     * Initializes an instance of ErrorModelClient client.
     * 
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param endpoint Service host.
     */
    public ErrorModelClientImpl(HttpPipeline httpPipeline, String endpoint) {
        this.httpPipeline = httpPipeline;
        this.endpoint = endpoint;
        this.errorOps = new ErrorOpsImpl(this);
    }
}
