// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the implementations for WireType.
 * Test for mismatch of wire type and client type on class constructors.
 * <!-- end generated doc -->
 */
package tsptest.wiretype.implementation;
