// Code generated by Microsoft (R) TypeSpec Code Generator.

package tsptest.specialchars;

import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.ServiceClient;
import io.clientcore.core.http.exceptions.HttpResponseException;
import io.clientcore.core.http.models.RequestOptions;
import io.clientcore.core.http.models.Response;
import io.clientcore.core.instrumentation.Instrumentation;
import io.clientcore.core.models.binarydata.BinaryData;
import tsptest.specialchars.implementation.BuiltinOpsImpl;
import tsptest.specialchars.implementation.models.ReadRequest;
import tsptest.specialchars.models.Resource;

/**
 * Initializes a new instance of the synchronous SpecialCharsClient type.
 */
@ServiceClient(builder = SpecialCharsClientBuilder.class)
public final class SpecialCharsClient {
    @Metadata(generated = true)
    private final BuiltinOpsImpl serviceClient;

    private final Instrumentation instrumentation;

    /**
     * Initializes an instance of SpecialCharsClient class.
     * 
     * @param serviceClient the service client implementation.
     * @param instrumentation the instrumentation instance.
     */
    @Metadata(generated = true)
    SpecialCharsClient(BuiltinOpsImpl serviceClient, Instrumentation instrumentation) {
        this.serviceClient = serviceClient;
        this.instrumentation = instrumentation;
    }

    /**
     * The read operation.
     * <p><strong>Request Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     id: String (Required)
     * }
     * }
     * </pre>
     * 
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     id: String (Required)
     *     aggregate: String (Optional)
     *     condition: String (Optional)
     *     requestName: String (Optional)
     *     value: Double (Optional)
     * }
     * }
     * </pre>
     * 
     * @param readRequest The readRequest parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    @Metadata(generated = true)
    public Response<Resource> readWithResponse(BinaryData readRequest, RequestOptions requestOptions) {
        return this.instrumentation.instrumentWithResponse("TspTest.SpecialChars.BuiltinOp.read", requestOptions,
            updatedOptions -> this.serviceClient.readWithResponse(readRequest, updatedOptions));
    }

    /**
     * The read operation.
     * 
     * @param id The id parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Metadata(generated = true)
    public Resource read(String id) {
        // Generated convenience method for readWithResponse
        RequestOptions requestOptions = new RequestOptions();
        ReadRequest readRequestObj = new ReadRequest(id);
        BinaryData readRequest = BinaryData.fromObject(readRequestObj);
        return readWithResponse(readRequest, requestOptions).getValue();
    }
}
