// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the classes for Fixed.
 * <!-- end generated doc -->
 */
package type.enums.fixed;
