// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the implementations for Builtin.
 * <!-- end generated doc -->
 */
package tsptest.builtin.implementation;
