// Code generated by Microsoft (R) TypeSpec Code Generator.

package tsptest.internal;

import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.ServiceClient;
import io.clientcore.core.http.exceptions.HttpResponseException;
import io.clientcore.core.http.models.RequestOptions;
import io.clientcore.core.http.models.Response;
import io.clientcore.core.instrumentation.Instrumentation;
import io.clientcore.core.models.binarydata.BinaryData;
import tsptest.internal.implementation.InternalOpsImpl;
import tsptest.internal.models.ApiRequest;
import tsptest.internal.models.ApiResponse;
import tsptest.internal.models.ResponseInternal;

/**
 * Initializes a new instance of the synchronous InternalClient type.
 */
@ServiceClient(builder = InternalClientBuilder.class)
public final class InternalClient {
    @Metadata(generated = true)
    private final InternalOpsImpl serviceClient;

    private final Instrumentation instrumentation;

    /**
     * Initializes an instance of InternalClient class.
     * 
     * @param serviceClient the service client implementation.
     * @param instrumentation the instrumentation instance.
     */
    @Metadata(generated = true)
    InternalClient(InternalOpsImpl serviceClient, Instrumentation instrumentation) {
        this.serviceClient = serviceClient;
        this.instrumentation = instrumentation;
    }

    /**
     * The postInternal operation.
     * <p><strong>Request Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     property (Required): {
     *         name: String (Required)
     *     }
     * }
     * }
     * </pre>
     * 
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     property (Required): {
     *         name: String (Required)
     *     }
     * }
     * }
     * </pre>
     * 
     * @param body The body parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    @Metadata(generated = true)
    public Response<ResponseInternal> postInternalWithResponse(BinaryData body, RequestOptions requestOptions) {
        return this.instrumentation.instrumentWithResponse("TspTest.Internal.InternalOp.postInternal", requestOptions,
            updatedOptions -> this.serviceClient.postInternalWithResponse(body, updatedOptions));
    }

    /**
     * The getInternal operation.
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     name: String (Required)
     * }
     * }
     * </pre>
     * 
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    @Metadata(generated = true)
    Response<ApiResponse> getInternalWithResponse(RequestOptions requestOptions) {
        return this.instrumentation.instrumentWithResponse("TspTest.Internal.InternalOp.getInternal", requestOptions,
            updatedOptions -> this.serviceClient.getInternalWithResponse(updatedOptions));
    }

    /**
     * The postProtocalInternal operation.
     * <p><strong>Request Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     name: String (Required)
     * }
     * }
     * </pre>
     * 
     * @param body The body parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    @Metadata(generated = true)
    Response<Void> postProtocalInternalWithResponse(BinaryData body, RequestOptions requestOptions) {
        return this.instrumentation.instrumentWithResponse("TspTest.Internal.InternalOp.postProtocalInternal",
            requestOptions,
            updatedOptions -> this.serviceClient.postProtocalInternalWithResponse(body, updatedOptions));
    }

    /**
     * The postInternal operation.
     * 
     * @param body The body parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Metadata(generated = true)
    public ResponseInternal postInternal(ApiRequest body) {
        // Generated convenience method for postInternalWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return postInternalWithResponse(BinaryData.fromObject(body), requestOptions).getValue();
    }

    /**
     * The getInternal operation.
     * 
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Metadata(generated = true)
    ApiResponse getInternal() {
        // Generated convenience method for getInternalWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return getInternalWithResponse(requestOptions).getValue();
    }
}
