// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the classes for Single.
 * Illustrates server with a single path parameter &#064;server.
 * <!-- end generated doc -->
 */
package server.path.single;
