// Code generated by Microsoft (R) TypeSpec Code Generator.

package tsptest.discriminatoredgecases;

import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.ServiceClient;
import io.clientcore.core.http.exceptions.HttpResponseException;
import io.clientcore.core.http.models.RequestOptions;
import io.clientcore.core.http.models.Response;
import io.clientcore.core.instrumentation.Instrumentation;
import tsptest.discriminatoredgecases.implementation.DiscriminatorEdgeCasesClientImpl;
import tsptest.discriminatoredgecases.models.ChildWithAnotherDiscriminator;
import tsptest.discriminatoredgecases.models.ChildWithRequiredPropertyAsDiscriminator;

/**
 * Initializes a new instance of the synchronous DiscriminatorEdgeCasesClient type.
 */
@ServiceClient(builder = DiscriminatorEdgeCasesClientBuilder.class)
public final class DiscriminatorEdgeCasesClient {
    @Metadata(generated = true)
    private final DiscriminatorEdgeCasesClientImpl serviceClient;

    private final Instrumentation instrumentation;

    /**
     * Initializes an instance of DiscriminatorEdgeCasesClient class.
     * 
     * @param serviceClient the service client implementation.
     * @param instrumentation the instrumentation instance.
     */
    @Metadata(generated = true)
    DiscriminatorEdgeCasesClient(DiscriminatorEdgeCasesClientImpl serviceClient, Instrumentation instrumentation) {
        this.serviceClient = serviceClient;
        this.instrumentation = instrumentation;
    }

    /**
     * The getChildRequiredDiscrim operation.
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     discriminator: String (Required)
     *     aProperty: String (Required)
     *     anotherProperty: String (Required)
     * }
     * }
     * </pre>
     * 
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    @Metadata(generated = true)
    public Response<ChildWithRequiredPropertyAsDiscriminator>
        getChildRequiredDiscrimWithResponse(RequestOptions requestOptions) {
        return this.instrumentation.instrumentWithResponse(
            "TspTest.DiscriminatorEdgeCases.DiscriminatorEdgeCasesOp.getChildRequiredDiscrim", requestOptions,
            updatedOptions -> this.serviceClient.getChildRequiredDiscrimWithResponse(updatedOptions));
    }

    /**
     * The getChildNewDiscrim operation.
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     discriminator: String (Required)
     *     aProperty: String (Required)
     *     differentDiscriminator: String (Required)
     *     yetAnotherProperty: String (Required)
     * }
     * }
     * </pre>
     * 
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    @Metadata(generated = true)
    public Response<ChildWithAnotherDiscriminator> getChildNewDiscrimWithResponse(RequestOptions requestOptions) {
        return this.instrumentation.instrumentWithResponse(
            "TspTest.DiscriminatorEdgeCases.DiscriminatorEdgeCasesOp.getChildNewDiscrim", requestOptions,
            updatedOptions -> this.serviceClient.getChildNewDiscrimWithResponse(updatedOptions));
    }

    /**
     * The getChildRequiredDiscrim operation.
     * 
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Metadata(generated = true)
    public ChildWithRequiredPropertyAsDiscriminator getChildRequiredDiscrim() {
        // Generated convenience method for getChildRequiredDiscrimWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return getChildRequiredDiscrimWithResponse(requestOptions).getValue();
    }

    /**
     * The getChildNewDiscrim operation.
     * 
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Metadata(generated = true)
    public ChildWithAnotherDiscriminator getChildNewDiscrim() {
        // Generated convenience method for getChildNewDiscrimWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return getChildNewDiscrimWithResponse(requestOptions).getValue();
    }
}
