// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the implementations for Basic.
 * Test for basic parameters cases.
 * <!-- end generated doc -->
 */
package parameters.basic.implementation;
