// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the implementations for ClientNamespace.
 * Illustrates the clientNamespace cases.
 * <!-- end generated doc -->
 */
package client.clientnamespace.implementation;
