// Code generated by Microsoft (R) TypeSpec Code Generator.

package tsptest.flatten.implementation.models;

import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.TypeConditions;
import io.clientcore.core.serialization.json.JsonReader;
import io.clientcore.core.serialization.json.JsonSerializable;
import io.clientcore.core.serialization.json.JsonToken;
import io.clientcore.core.serialization.json.JsonWriter;
import java.io.IOException;

/**
 * The SendProjectedNameRequest model.
 */
@Metadata(conditions = { TypeConditions.IMMUTABLE })
public final class SendProjectedNameRequest implements JsonSerializable<SendProjectedNameRequest> {
    /*
     * The file_id property.
     */
    @Metadata(generated = true)
    private final String fileIdentifier;

    /**
     * Creates an instance of SendProjectedNameRequest class.
     * 
     * @param fileIdentifier the fileIdentifier value to set.
     */
    @Metadata(generated = true)
    public SendProjectedNameRequest(String fileIdentifier) {
        this.fileIdentifier = fileIdentifier;
    }

    /**
     * Get the fileIdentifier property: The file_id property.
     * 
     * @return the fileIdentifier value.
     */
    @Metadata(generated = true)
    public String getFileIdentifier() {
        return this.fileIdentifier;
    }

    /**
     * {@inheritDoc}
     */
    @Metadata(generated = true)
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("file_id", this.fileIdentifier);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of SendProjectedNameRequest from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of SendProjectedNameRequest if the JsonReader was pointing to an instance of it, or null if
     * it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the SendProjectedNameRequest.
     */
    @Metadata(generated = true)
    public static SendProjectedNameRequest fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String fileIdentifier = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("file_id".equals(fieldName)) {
                    fileIdentifier = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            return new SendProjectedNameRequest(fileIdentifier);
        });
    }
}
