// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the implementations for ProtocolAndConvenient.
 * <!-- end generated doc -->
 */
package tsptest.protocolandconvenient.implementation;
