// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the classes for Standard.
 * Illustrates bodies templated with Azure Core with long-running operation.
 * <!-- end generated doc -->
 */
package azure.core.lro.standard;
