// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the data models for NotDiscriminated.
 * Illustrates not-discriminated inheritance model.
 * <!-- end generated doc -->
 */
package type.model.inheritance.notdiscriminated.models;
