// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the implementations for Union.
 * <!-- end generated doc -->
 */
package tsptest.union.implementation;
