// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the data models for Usage.
 * Illustrates usage of Record in different places(Operation parameters, return type or both).
 * <!-- end generated doc -->
 */
package type.model.usage.models;
