// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the implementations for DurationModel.
 * Test for encode decorator on duration.
 * <!-- end generated doc -->
 */
package encode.duration.implementation;
