// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the implementations for ApiKey.
 * Illustrates clients generated with ApiKey authentication.
 * <!-- end generated doc -->
 */
package authentication.apikey.implementation;
