// Code generated by Microsoft (R) TypeSpec Code Generator.

package client.naming.implementation;

import io.clientcore.core.annotations.ServiceInterface;
import io.clientcore.core.http.RestProxy;
import io.clientcore.core.http.annotations.BodyParam;
import io.clientcore.core.http.annotations.HeaderParam;
import io.clientcore.core.http.annotations.HostParam;
import io.clientcore.core.http.annotations.HttpRequestInformation;
import io.clientcore.core.http.annotations.UnexpectedResponseExceptionDetail;
import io.clientcore.core.http.exceptions.HttpResponseException;
import io.clientcore.core.http.models.HttpMethod;
import io.clientcore.core.http.models.RequestOptions;
import io.clientcore.core.http.models.Response;
import io.clientcore.core.http.pipeline.HttpPipeline;
import io.clientcore.core.models.binarydata.BinaryData;
import io.clientcore.core.serialization.ObjectSerializer;
import java.lang.reflect.InvocationTargetException;

/**
 * An instance of this class provides access to all the operations defined in UnionEnums.
 */
public final class UnionEnumsImpl {
    /**
     * The proxy service used to perform REST calls.
     */
    private final UnionEnumsService service;

    /**
     * The service client containing this operation class.
     */
    private final NamingClientImpl client;

    /**
     * Initializes an instance of UnionEnumsImpl.
     * 
     * @param client the instance of the service client containing this operation class.
     */
    UnionEnumsImpl(NamingClientImpl client) {
        this.service = RestProxy.create(UnionEnumsService.class, client.getHttpPipeline());
        this.client = client;
    }

    /**
     * The interface defining all the services for NamingClientUnionEnums to be used by the proxy service to perform
     * REST calls.
     */
    @ServiceInterface(name = "NamingClientUnionEnu", host = "{endpoint}")
    public interface UnionEnumsService {
        static UnionEnumsService getNewInstance(HttpPipeline pipeline, ObjectSerializer serializer) {
            try {
                Class<?> clazz = Class.forName("client.naming.implementation.UnionEnumsServiceImpl");
                return (UnionEnumsService) clazz.getMethod("getNewInstance", HttpPipeline.class, ObjectSerializer.class)
                    .invoke(null, pipeline, serializer);
            } catch (ClassNotFoundException | NoSuchMethodException | IllegalAccessException
                | InvocationTargetException e) {
                throw new RuntimeException(e);
            }

        }

        @HttpRequestInformation(
            method = HttpMethod.POST,
            path = "/client/naming/union-enum/union-enum-name",
            expectedStatusCodes = { 204 })
        @UnexpectedResponseExceptionDetail
        Response<Void> unionEnumName(@HostParam("endpoint") String endpoint,
            @HeaderParam("Content-Type") String contentType, @BodyParam("application/json") BinaryData body,
            RequestOptions requestOptions);

        @HttpRequestInformation(
            method = HttpMethod.POST,
            path = "/client/naming/union-enum/union-enum-name",
            expectedStatusCodes = { 204 })
        @UnexpectedResponseExceptionDetail
        default void unionEnumName(@HostParam("endpoint") String endpoint,
            @HeaderParam("Content-Type") String contentType, @BodyParam("application/json") BinaryData body) {
            unionEnumName(endpoint, contentType, body, null);
        }

        @HttpRequestInformation(
            method = HttpMethod.POST,
            path = "/client/naming/union-enum/union-enum-member-name",
            expectedStatusCodes = { 204 })
        @UnexpectedResponseExceptionDetail
        Response<Void> unionEnumMemberName(@HostParam("endpoint") String endpoint,
            @HeaderParam("Content-Type") String contentType, @BodyParam("application/json") BinaryData body,
            RequestOptions requestOptions);

        @HttpRequestInformation(
            method = HttpMethod.POST,
            path = "/client/naming/union-enum/union-enum-member-name",
            expectedStatusCodes = { 204 })
        @UnexpectedResponseExceptionDetail
        default void unionEnumMemberName(@HostParam("endpoint") String endpoint,
            @HeaderParam("Content-Type") String contentType, @BodyParam("application/json") BinaryData body) {
            unionEnumMemberName(endpoint, contentType, body, null);
        }
    }

    /**
     * The unionEnumName operation.
     * <p><strong>Request Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * String(value1)
     * }
     * </pre>
     * 
     * @param body The body parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    public Response<Void> unionEnumNameWithResponse(BinaryData body, RequestOptions requestOptions) {
        final String contentType = "application/json";
        return service.unionEnumName(this.client.getEndpoint(), contentType, body, requestOptions);
    }

    /**
     * The unionEnumMemberName operation.
     * <p><strong>Request Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * String(value1/value2)
     * }
     * </pre>
     * 
     * @param body The body parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    public Response<Void> unionEnumMemberNameWithResponse(BinaryData body, RequestOptions requestOptions) {
        final String contentType = "application/json";
        return service.unionEnumMemberName(this.client.getEndpoint(), contentType, body, requestOptions);
    }
}
