// Code generated by Microsoft (R) TypeSpec Code Generator.

package azure.core.page.models;

import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.TypeConditions;
import io.clientcore.core.serialization.json.JsonReader;
import io.clientcore.core.serialization.json.JsonSerializable;
import io.clientcore.core.serialization.json.JsonToken;
import io.clientcore.core.serialization.json.JsonWriter;
import java.io.IOException;

/**
 * Second item.
 */
@Metadata(conditions = { TypeConditions.IMMUTABLE })
public final class SecondItem implements JsonSerializable<SecondItem> {
    /*
     * The name of the item.
     */
    @Metadata(generated = true)
    private String name;

    /**
     * Creates an instance of SecondItem class.
     */
    @Metadata(generated = true)
    private SecondItem() {
    }

    /**
     * Get the name property: The name of the item.
     * 
     * @return the name value.
     */
    @Metadata(generated = true)
    public String getName() {
        return this.name;
    }

    /**
     * {@inheritDoc}
     */
    @Metadata(generated = true)
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of SecondItem from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of SecondItem if the JsonReader was pointing to an instance of it, or null if it was pointing
     * to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the SecondItem.
     */
    @Metadata(generated = true)
    public static SecondItem fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            SecondItem deserializedSecondItem = new SecondItem();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("name".equals(fieldName)) {
                    deserializedSecondItem.name = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedSecondItem;
        });
    }
}
