// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the implementations for OAuth2.
 * Illustrates clients generated with OAuth2 authentication.
 * <!-- end generated doc -->
 */
package authentication.oauth2.implementation;
