// Code generated by Microsoft (R) TypeSpec Code Generator.

package azure.core.scalar.implementation;

import azure.core.scalar.ScalarServiceVersion;
import io.clientcore.core.http.pipeline.HttpPipeline;

/**
 * Initializes a new instance of the ScalarClient type.
 */
public final class ScalarClientImpl {
    /**
     * Service host.
     */
    private final String endpoint;

    /**
     * Gets Service host.
     * 
     * @return the endpoint value.
     */
    public String getEndpoint() {
        return this.endpoint;
    }

    /**
     * Service version.
     */
    private final ScalarServiceVersion serviceVersion;

    /**
     * Gets Service version.
     * 
     * @return the serviceVersion value.
     */
    public ScalarServiceVersion getServiceVersion() {
        return this.serviceVersion;
    }

    /**
     * The HTTP pipeline to send requests through.
     */
    private final HttpPipeline httpPipeline;

    /**
     * Gets The HTTP pipeline to send requests through.
     * 
     * @return the httpPipeline value.
     */
    public HttpPipeline getHttpPipeline() {
        return this.httpPipeline;
    }

    /**
     * The AzureLocationScalarsImpl object to access its operations.
     */
    private final AzureLocationScalarsImpl azureLocationScalars;

    /**
     * Gets the AzureLocationScalarsImpl object to access its operations.
     * 
     * @return the AzureLocationScalarsImpl object.
     */
    public AzureLocationScalarsImpl getAzureLocationScalars() {
        return this.azureLocationScalars;
    }

    /**
     * Initializes an instance of ScalarClient client.
     * 
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param endpoint Service host.
     * @param serviceVersion Service version.
     */
    public ScalarClientImpl(HttpPipeline httpPipeline, String endpoint, ScalarServiceVersion serviceVersion) {
        this.httpPipeline = httpPipeline;
        this.endpoint = endpoint;
        this.serviceVersion = serviceVersion;
        this.azureLocationScalars = new AzureLocationScalarsImpl(this);
    }
}
