// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the classes for Dictionary.
 * Illustrates various of dictionaries.
 * <!-- end generated doc -->
 */
package type.dictionary;
