// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the implementations for DiscriminatorEdgeCases.
 * <!-- end generated doc -->
 */
package tsptest.discriminatoredgecases.implementation;
