// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the classes for EnumService.
 * <!-- end generated doc -->
 */
package tsptest.enumservice;
