// Code generated by Microsoft (R) TypeSpec Code Generator.

package tsptest.optional.models;

import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.TypeConditions;
import io.clientcore.core.serialization.json.JsonReader;
import io.clientcore.core.serialization.json.JsonSerializable;
import io.clientcore.core.serialization.json.JsonToken;
import io.clientcore.core.serialization.json.JsonWriter;
import java.io.IOException;

/**
 * The ImmutableModel model.
 */
@Metadata(conditions = { TypeConditions.IMMUTABLE })
public final class ImmutableModel implements JsonSerializable<ImmutableModel> {
    /*
     * The stringReadWriteRequired property.
     */
    @Metadata(generated = true)
    private final String stringReadWriteRequired;

    /*
     * The stringReadOnlyOptional property.
     */
    @Metadata(generated = true)
    private String stringReadOnlyOptional;

    /**
     * Creates an instance of ImmutableModel class.
     * 
     * @param stringReadWriteRequired the stringReadWriteRequired value to set.
     */
    @Metadata(generated = true)
    private ImmutableModel(String stringReadWriteRequired) {
        this.stringReadWriteRequired = stringReadWriteRequired;
    }

    /**
     * Get the stringReadWriteRequired property: The stringReadWriteRequired property.
     * 
     * @return the stringReadWriteRequired value.
     */
    @Metadata(generated = true)
    public String getStringReadWriteRequired() {
        return this.stringReadWriteRequired;
    }

    /**
     * Get the stringReadOnlyOptional property: The stringReadOnlyOptional property.
     * 
     * @return the stringReadOnlyOptional value.
     */
    @Metadata(generated = true)
    public String getStringReadOnlyOptional() {
        return this.stringReadOnlyOptional;
    }

    /**
     * {@inheritDoc}
     */
    @Metadata(generated = true)
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("stringReadWriteRequired", this.stringReadWriteRequired);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of ImmutableModel from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of ImmutableModel if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the ImmutableModel.
     */
    @Metadata(generated = true)
    public static ImmutableModel fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String stringReadWriteRequired = null;
            String stringReadOnlyOptional = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("stringReadWriteRequired".equals(fieldName)) {
                    stringReadWriteRequired = reader.getString();
                } else if ("stringReadOnlyOptional".equals(fieldName)) {
                    stringReadOnlyOptional = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            ImmutableModel deserializedImmutableModel = new ImmutableModel(stringReadWriteRequired);
            deserializedImmutableModel.stringReadOnlyOptional = stringReadOnlyOptional;

            return deserializedImmutableModel;
        });
    }
}
