// Code generated by Microsoft (R) TypeSpec Code Generator.

package tsptest.errormodel.models;

import azure.core.foundations.models.Error;
import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.TypeConditions;
import io.clientcore.core.serialization.json.JsonReader;
import io.clientcore.core.serialization.json.JsonSerializable;
import io.clientcore.core.serialization.json.JsonToken;
import io.clientcore.core.serialization.json.JsonWriter;
import java.io.IOException;

/**
 * The Diagnostic model.
 */
@Metadata(conditions = { TypeConditions.IMMUTABLE })
public final class Diagnostic implements JsonSerializable<Diagnostic> {
    /*
     * The name property.
     */
    @Metadata(generated = true)
    private final String name;

    /*
     * The error property.
     */
    @Metadata(generated = true)
    private final Error error;

    /**
     * Creates an instance of Diagnostic class.
     * 
     * @param name the name value to set.
     * @param error the error value to set.
     */
    @Metadata(generated = true)
    private Diagnostic(String name, Error error) {
        this.name = name;
        this.error = error;
    }

    /**
     * Get the name property: The name property.
     * 
     * @return the name value.
     */
    @Metadata(generated = true)
    public String getName() {
        return this.name;
    }

    /**
     * Get the error property: The error property.
     * 
     * @return the error value.
     */
    @Metadata(generated = true)
    public Error getError() {
        return this.error;
    }

    /**
     * {@inheritDoc}
     */
    @Metadata(generated = true)
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("name", this.name);
        jsonWriter.writeJsonField("error", this.error);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of Diagnostic from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of Diagnostic if the JsonReader was pointing to an instance of it, or null if it was pointing
     * to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the Diagnostic.
     */
    @Metadata(generated = true)
    public static Diagnostic fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String name = null;
            Error error = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("name".equals(fieldName)) {
                    name = reader.getString();
                } else if ("error".equals(fieldName)) {
                    error = Error.fromJson(reader);
                } else {
                    reader.skipChildren();
                }
            }
            return new Diagnostic(name, error);
        });
    }
}
