// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the implementations for MethodOverride.
 * <!-- end generated doc -->
 */
package methodoverride.implementation;
