// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the classes for Pageable.
 * Test describing pageable.
 * <!-- end generated doc -->
 */
package azure.payload.pageable;
