// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the classes for DatetimeModel.
 * Test for encode decorator on datetime.
 * <!-- end generated doc -->
 */
package encode.datetime;
