// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the implementations for Versioned.
 * Illustrates versioned server.
 * <!-- end generated doc -->
 */
package server.versions.versioned.implementation;
