// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the data models for Internal.
 * <!-- end generated doc -->
 */
package tsptest.internal.implementation.models;
