// Code generated by Microsoft (R) TypeSpec Code Generator.

package client.clientnamespace.second.models;

import client.clientnamespace.second.sub.models.SecondClientEnumType;
import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.TypeConditions;
import io.clientcore.core.serialization.json.JsonReader;
import io.clientcore.core.serialization.json.JsonSerializable;
import io.clientcore.core.serialization.json.JsonToken;
import io.clientcore.core.serialization.json.JsonWriter;
import java.io.IOException;

/**
 * The SecondClientResult model.
 */
@Metadata(conditions = { TypeConditions.IMMUTABLE })
public final class SecondClientResult implements JsonSerializable<SecondClientResult> {
    /*
     * The type property.
     */
    @Metadata(generated = true)
    private final SecondClientEnumType type;

    /**
     * Creates an instance of SecondClientResult class.
     * 
     * @param type the type value to set.
     */
    @Metadata(generated = true)
    private SecondClientResult(SecondClientEnumType type) {
        this.type = type;
    }

    /**
     * Get the type property: The type property.
     * 
     * @return the type value.
     */
    @Metadata(generated = true)
    public SecondClientEnumType getType() {
        return this.type;
    }

    /**
     * {@inheritDoc}
     */
    @Metadata(generated = true)
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("type", this.type == null ? null : this.type.getValue());
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of SecondClientResult from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of SecondClientResult if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the SecondClientResult.
     */
    @Metadata(generated = true)
    public static SecondClientResult fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            SecondClientEnumType type = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("type".equals(fieldName)) {
                    type = SecondClientEnumType.fromValue(reader.getString());
                } else {
                    reader.skipChildren();
                }
            }
            return new SecondClientResult(type);
        });
    }
}
