// Code generated by Microsoft (R) TypeSpec Code Generator.

package client.structure.service;

import client.structure.service.implementation.QuxesImpl;
import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.ServiceClient;
import io.clientcore.core.http.exceptions.HttpResponseException;
import io.clientcore.core.http.models.RequestOptions;
import io.clientcore.core.http.models.Response;
import io.clientcore.core.instrumentation.Instrumentation;

/**
 * Initializes a new instance of the synchronous ServiceClientClient type.
 */
@ServiceClient(builder = ServiceClientClientBuilder.class)
public final class QuxClient {
    @Metadata(generated = true)
    private final QuxesImpl serviceClient;

    private final Instrumentation instrumentation;

    /**
     * Initializes an instance of QuxClient class.
     * 
     * @param serviceClient the service client implementation.
     * @param instrumentation the instrumentation instance.
     */
    @Metadata(generated = true)
    QuxClient(QuxesImpl serviceClient, Instrumentation instrumentation) {
        this.serviceClient = serviceClient;
        this.instrumentation = instrumentation;
    }

    /**
     * The eight operation.
     * 
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    @Metadata(generated = true)
    public Response<Void> eightWithResponse(RequestOptions requestOptions) {
        return this.instrumentation.instrumentWithResponse("Client.Structure.Service.Qux.eight", requestOptions,
            updatedOptions -> this.serviceClient.eightWithResponse(updatedOptions));
    }

    /**
     * The eight operation.
     * 
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Metadata(generated = true)
    public void eight() {
        // Generated convenience method for eightWithResponse
        RequestOptions requestOptions = new RequestOptions();
        eightWithResponse(requestOptions).getValue();
    }
}
