// Code generated by Microsoft (R) TypeSpec Code Generator.

package routes.implementation;

import io.clientcore.core.annotations.ServiceInterface;
import io.clientcore.core.http.RestProxy;
import io.clientcore.core.http.annotations.HostParam;
import io.clientcore.core.http.annotations.HttpRequestInformation;
import io.clientcore.core.http.annotations.QueryParam;
import io.clientcore.core.http.annotations.UnexpectedResponseExceptionDetail;
import io.clientcore.core.http.exceptions.HttpResponseException;
import io.clientcore.core.http.models.HttpMethod;
import io.clientcore.core.http.models.RequestOptions;
import io.clientcore.core.http.models.Response;
import io.clientcore.core.http.pipeline.HttpPipeline;
import io.clientcore.core.serialization.ObjectSerializer;
import java.lang.reflect.InvocationTargetException;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

/**
 * An instance of this class provides access to all the operations defined in QueryParametersQueryExpansionStandards.
 */
public final class QueryParametersQueryExpansionStandardsImpl {
    /**
     * The proxy service used to perform REST calls.
     */
    private final QueryParametersQueryExpansionStandardsService service;

    /**
     * The service client containing this operation class.
     */
    private final RoutesClientImpl client;

    /**
     * Initializes an instance of QueryParametersQueryExpansionStandardsImpl.
     * 
     * @param client the instance of the service client containing this operation class.
     */
    QueryParametersQueryExpansionStandardsImpl(RoutesClientImpl client) {
        this.service = RestProxy.create(QueryParametersQueryExpansionStandardsService.class, client.getHttpPipeline());
        this.client = client;
    }

    /**
     * The interface defining all the services for RoutesClientQueryParametersQueryExpansionStandards to be used by the
     * proxy service to perform REST calls.
     */
    @ServiceInterface(name = "RoutesClientQueryPar", host = "{endpoint}")
    public interface QueryParametersQueryExpansionStandardsService {
        static QueryParametersQueryExpansionStandardsService getNewInstance(HttpPipeline pipeline,
            ObjectSerializer serializer) {
            try {
                Class<?> clazz
                    = Class.forName("routes.implementation.QueryParametersQueryExpansionStandardsServiceImpl");
                return (QueryParametersQueryExpansionStandardsService) clazz
                    .getMethod("getNewInstance", HttpPipeline.class, ObjectSerializer.class)
                    .invoke(null, pipeline, serializer);
            } catch (ClassNotFoundException | NoSuchMethodException | IllegalAccessException
                | InvocationTargetException e) {
                throw new RuntimeException(e);
            }

        }

        @HttpRequestInformation(
            method = HttpMethod.GET,
            path = "/routes/query/query-expansion/standard/primitive",
            expectedStatusCodes = { 204 })
        @UnexpectedResponseExceptionDetail
        Response<Void> primitive(@HostParam("endpoint") String endpoint, @QueryParam("param") String param,
            RequestOptions requestOptions);

        @HttpRequestInformation(
            method = HttpMethod.GET,
            path = "/routes/query/query-expansion/standard/primitive",
            expectedStatusCodes = { 204 })
        @UnexpectedResponseExceptionDetail
        default void primitive(@HostParam("endpoint") String endpoint, @QueryParam("param") String param) {
            primitive(endpoint, param, null);
        }

        @HttpRequestInformation(
            method = HttpMethod.GET,
            path = "/routes/query/query-expansion/standard/array",
            expectedStatusCodes = { 204 })
        @UnexpectedResponseExceptionDetail
        Response<Void> array(@HostParam("endpoint") String endpoint, @QueryParam("param") String param,
            RequestOptions requestOptions);

        @HttpRequestInformation(
            method = HttpMethod.GET,
            path = "/routes/query/query-expansion/standard/array",
            expectedStatusCodes = { 204 })
        @UnexpectedResponseExceptionDetail
        default void array(@HostParam("endpoint") String endpoint, @QueryParam("param") String param) {
            array(endpoint, param, null);
        }

        @HttpRequestInformation(
            method = HttpMethod.GET,
            path = "/routes/query/query-expansion/standard/record",
            expectedStatusCodes = { 204 })
        @UnexpectedResponseExceptionDetail
        Response<Void> record(@HostParam("endpoint") String endpoint, @QueryParam("param") Map<String, Integer> param,
            RequestOptions requestOptions);

        @HttpRequestInformation(
            method = HttpMethod.GET,
            path = "/routes/query/query-expansion/standard/record",
            expectedStatusCodes = { 204 })
        @UnexpectedResponseExceptionDetail
        default void record(@HostParam("endpoint") String endpoint, @QueryParam("param") Map<String, Integer> param) {
            record(endpoint, param, null);
        }
    }

    /**
     * The primitive operation.
     * 
     * @param param The param parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    public Response<Void> primitiveWithResponse(String param, RequestOptions requestOptions) {
        return service.primitive(this.client.getEndpoint(), param, requestOptions);
    }

    /**
     * The array operation.
     * 
     * @param param The param parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    public Response<Void> arrayWithResponse(List<String> param, RequestOptions requestOptions) {
        String paramConverted = param.stream()
            .map(paramItemValue -> Objects.toString(paramItemValue, ""))
            .collect(Collectors.joining(","));
        return service.array(this.client.getEndpoint(), paramConverted, requestOptions);
    }

    /**
     * The record operation.
     * 
     * @param param The param parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    public Response<Void> recordWithResponse(Map<String, Integer> param, RequestOptions requestOptions) {
        return service.record(this.client.getEndpoint(), param, requestOptions);
    }
}
