// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the classes for Header.
 * <!-- end generated doc -->
 */
package azure.clientgenerator.core.apiversion.header;
