// Code generated by Microsoft (R) TypeSpec Code Generator.

package encode.bytes.implementation;

import io.clientcore.core.annotations.ServiceInterface;
import io.clientcore.core.http.RestProxy;
import io.clientcore.core.http.annotations.HeaderParam;
import io.clientcore.core.http.annotations.HostParam;
import io.clientcore.core.http.annotations.HttpRequestInformation;
import io.clientcore.core.http.annotations.UnexpectedResponseExceptionDetail;
import io.clientcore.core.http.exceptions.HttpResponseException;
import io.clientcore.core.http.models.HttpMethod;
import io.clientcore.core.http.models.RequestOptions;
import io.clientcore.core.http.models.Response;
import io.clientcore.core.http.pipeline.HttpPipeline;
import io.clientcore.core.models.binarydata.BinaryData;
import io.clientcore.core.serialization.ObjectSerializer;
import io.clientcore.core.utils.Base64Url;
import io.clientcore.core.utils.Base64Util;
import java.lang.reflect.InvocationTargetException;
import java.util.List;
import java.util.stream.Collectors;

/**
 * An instance of this class provides access to all the operations defined in Headers.
 */
public final class HeadersImpl {
    /**
     * The proxy service used to perform REST calls.
     */
    private final HeadersService service;

    /**
     * The service client containing this operation class.
     */
    private final BytesClientImpl client;

    /**
     * Initializes an instance of HeadersImpl.
     * 
     * @param client the instance of the service client containing this operation class.
     */
    HeadersImpl(BytesClientImpl client) {
        this.service = RestProxy.create(HeadersService.class, client.getHttpPipeline());
        this.client = client;
    }

    /**
     * The interface defining all the services for BytesClientHeaders to be used by the proxy service to perform REST
     * calls.
     */
    @ServiceInterface(name = "BytesClientHeaders", host = "{endpoint}")
    public interface HeadersService {
        static HeadersService getNewInstance(HttpPipeline pipeline, ObjectSerializer serializer) {
            try {
                Class<?> clazz = Class.forName("encode.bytes.implementation.HeadersServiceImpl");
                return (HeadersService) clazz.getMethod("getNewInstance", HttpPipeline.class, ObjectSerializer.class)
                    .invoke(null, pipeline, serializer);
            } catch (ClassNotFoundException | NoSuchMethodException | IllegalAccessException
                | InvocationTargetException e) {
                throw new RuntimeException(e);
            }

        }

        @HttpRequestInformation(
            method = HttpMethod.GET,
            path = "/encode/bytes/header/default",
            expectedStatusCodes = { 204 })
        @UnexpectedResponseExceptionDetail
        Response<Void> defaultMethod(@HostParam("endpoint") String endpoint, @HeaderParam("value") String value,
            RequestOptions requestOptions);

        @HttpRequestInformation(
            method = HttpMethod.GET,
            path = "/encode/bytes/header/default",
            expectedStatusCodes = { 204 })
        @UnexpectedResponseExceptionDetail
        default void defaultMethod(@HostParam("endpoint") String endpoint, @HeaderParam("value") String value) {
            defaultMethod(endpoint, value, null);
        }

        @HttpRequestInformation(
            method = HttpMethod.GET,
            path = "/encode/bytes/header/base64",
            expectedStatusCodes = { 204 })
        @UnexpectedResponseExceptionDetail
        Response<Void> base64(@HostParam("endpoint") String endpoint, @HeaderParam("value") String value,
            RequestOptions requestOptions);

        @HttpRequestInformation(
            method = HttpMethod.GET,
            path = "/encode/bytes/header/base64",
            expectedStatusCodes = { 204 })
        @UnexpectedResponseExceptionDetail
        default void base64(@HostParam("endpoint") String endpoint, @HeaderParam("value") String value) {
            base64(endpoint, value, null);
        }

        @HttpRequestInformation(
            method = HttpMethod.GET,
            path = "/encode/bytes/header/base64url",
            expectedStatusCodes = { 204 })
        @UnexpectedResponseExceptionDetail
        Response<Void> base64url(@HostParam("endpoint") String endpoint, @HeaderParam("value") Base64Url value,
            RequestOptions requestOptions);

        @HttpRequestInformation(
            method = HttpMethod.GET,
            path = "/encode/bytes/header/base64url",
            expectedStatusCodes = { 204 })
        @UnexpectedResponseExceptionDetail
        default void base64url(@HostParam("endpoint") String endpoint, @HeaderParam("value") Base64Url value) {
            base64url(endpoint, value, null);
        }

        @HttpRequestInformation(
            method = HttpMethod.GET,
            path = "/encode/bytes/header/base64url-array",
            expectedStatusCodes = { 204 })
        @UnexpectedResponseExceptionDetail
        Response<Void> base64urlArray(@HostParam("endpoint") String endpoint, @HeaderParam("value") String value,
            RequestOptions requestOptions);

        @HttpRequestInformation(
            method = HttpMethod.GET,
            path = "/encode/bytes/header/base64url-array",
            expectedStatusCodes = { 204 })
        @UnexpectedResponseExceptionDetail
        default void base64urlArray(@HostParam("endpoint") String endpoint, @HeaderParam("value") String value) {
            base64urlArray(endpoint, value, null);
        }
    }

    /**
     * The defaultMethod operation.
     * 
     * @param value The value parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    public Response<Void> defaultMethodWithResponse(byte[] value, RequestOptions requestOptions) {
        String valueConverted = Base64Util.encodeToString(value);
        return service.defaultMethod(this.client.getEndpoint(), valueConverted, requestOptions);
    }

    /**
     * The base64 operation.
     * 
     * @param value The value parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    public Response<Void> base64WithResponse(byte[] value, RequestOptions requestOptions) {
        String valueConverted = Base64Util.encodeToString(value);
        return service.base64(this.client.getEndpoint(), valueConverted, requestOptions);
    }

    /**
     * The base64url operation.
     * 
     * @param value The value parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    public Response<Void> base64urlWithResponse(byte[] value, RequestOptions requestOptions) {
        Base64Url valueConverted = Base64Url.encode(value);
        return service.base64url(this.client.getEndpoint(), valueConverted, requestOptions);
    }

    /**
     * The base64urlArray operation.
     * 
     * @param value The value parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    public Response<Void> base64urlArrayWithResponse(List<byte[]> value, RequestOptions requestOptions) {
        String valueConverted = value.stream()
            .map(paramItemValue -> Base64Url.encode(paramItemValue))
            .collect(Collectors.toList())
            .stream()
            .map(paramItemValue -> {
                if (paramItemValue == null) {
                    return "";
                } else {
                    String itemValueString = BinaryData.fromObject(paramItemValue).toString();
                    int strLength = itemValueString.length();
                    int startOffset = 0;
                    while (startOffset < strLength) {
                        if (itemValueString.charAt(startOffset) != '"') {
                            break;
                        }
                        startOffset++;
                    }
                    if (startOffset == strLength) {
                        return "";
                    }
                    int endOffset = strLength - 1;
                    while (endOffset >= 0) {
                        if (itemValueString.charAt(endOffset) != '"') {
                            break;
                        }

                        endOffset--;
                    }
                    return itemValueString.substring(startOffset, endOffset + 1);
                }
            })
            .collect(Collectors.joining(","));
        return service.base64urlArray(this.client.getEndpoint(), valueConverted, requestOptions);
    }
}
