// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the implementations for Bytes.
 * Test for encode decorator on bytes.
 * <!-- end generated doc -->
 */
package encode.bytes.implementation;
