// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the data models for Array.
 * Illustrates various types of arrays.
 * <!-- end generated doc -->
 */
package type.array.models;
