// Code generated by Microsoft (R) TypeSpec Code Generator.

package methodoverride.models;

import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.TypeConditions;

/**
 * The GroupPartOptions model.
 */
@Metadata(conditions = { TypeConditions.FLUENT })
public final class GroupPartOptions {
    /*
     * The bar property.
     */
    @Metadata(generated = true)
    private String bar;

    /*
     * The prop2 property.
     */
    @Metadata(generated = true)
    private String prop2;

    /**
     * Creates an instance of GroupPartOptions class.
     */
    @Metadata(generated = true)
    public GroupPartOptions() {
    }

    /**
     * Get the bar property: The bar property.
     * 
     * @return the bar value.
     */
    @Metadata(generated = true)
    public String getBar() {
        return this.bar;
    }

    /**
     * Set the bar property: The bar property.
     * 
     * @param bar the bar value to set.
     * @return the GroupPartOptions object itself.
     */
    @Metadata(generated = true)
    public GroupPartOptions setBar(String bar) {
        this.bar = bar;
        return this;
    }

    /**
     * Get the prop2 property: The prop2 property.
     * 
     * @return the prop2 value.
     */
    @Metadata(generated = true)
    public String getProp2() {
        return this.prop2;
    }

    /**
     * Set the prop2 property: The prop2 property.
     * 
     * @param prop2 the prop2 value to set.
     * @return the GroupPartOptions object itself.
     */
    @Metadata(generated = true)
    public GroupPartOptions setProp2(String prop2) {
        this.prop2 = prop2;
        return this;
    }
}
