// Code generated by Microsoft (R) TypeSpec Code Generator.

package methodoverride.models;

import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.TypeConditions;

/**
 * The GroupQueryOptions model.
 */
@Metadata(conditions = { TypeConditions.FLUENT })
public final class GroupQueryOptions {
    /*
     * The foo property.
     */
    @Metadata(generated = true)
    private String foo;

    /*
     * The bar property.
     */
    @Metadata(generated = true)
    private String bar;

    /**
     * Creates an instance of GroupQueryOptions class.
     */
    @Metadata(generated = true)
    public GroupQueryOptions() {
    }

    /**
     * Get the foo property: The foo property.
     * 
     * @return the foo value.
     */
    @Metadata(generated = true)
    public String getFoo() {
        return this.foo;
    }

    /**
     * Set the foo property: The foo property.
     * 
     * @param foo the foo value to set.
     * @return the GroupQueryOptions object itself.
     */
    @Metadata(generated = true)
    public GroupQueryOptions setFoo(String foo) {
        this.foo = foo;
        return this;
    }

    /**
     * Get the bar property: The bar property.
     * 
     * @return the bar value.
     */
    @Metadata(generated = true)
    public String getBar() {
        return this.bar;
    }

    /**
     * Set the bar property: The bar property.
     * 
     * @param bar the bar value to set.
     * @return the GroupQueryOptions object itself.
     */
    @Metadata(generated = true)
    public GroupQueryOptions setBar(String bar) {
        this.bar = bar;
        return this;
    }
}
