// Code generated by Microsoft (R) TypeSpec Code Generator.

package azure.clientgenerator.core.access;

import azure.clientgenerator.core.access.implementation.RelativeModelInOperationsImpl;
import azure.clientgenerator.core.access.relativemodelinoperation.implementation.models.AbstractModel;
import azure.clientgenerator.core.access.relativemodelinoperation.implementation.models.OuterModel;
import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.ServiceClient;
import io.clientcore.core.http.exceptions.HttpResponseException;
import io.clientcore.core.http.models.RequestOptions;
import io.clientcore.core.http.models.Response;
import io.clientcore.core.instrumentation.Instrumentation;

/**
 * Initializes a new instance of the synchronous AccessClient type.
 */
@ServiceClient(builder = AccessClientBuilder.class)
public final class RelativeModelInOperationClient {
    @Metadata(generated = true)
    private final RelativeModelInOperationsImpl serviceClient;

    private final Instrumentation instrumentation;

    /**
     * Initializes an instance of RelativeModelInOperationClient class.
     * 
     * @param serviceClient the service client implementation.
     * @param instrumentation the instrumentation instance.
     */
    @Metadata(generated = true)
    RelativeModelInOperationClient(RelativeModelInOperationsImpl serviceClient, Instrumentation instrumentation) {
        this.serviceClient = serviceClient;
        this.instrumentation = instrumentation;
    }

    /**
     * Expected query parameter: name="Madge"
     * Expected response body:
     * ```json
     * {
     * "name": "Madge",
     * "inner":
     * {
     * "name": "Madge"
     * }
     * }
     * ```.
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     name: String (Required)
     *     inner (Required): {
     *         name: String (Required)
     *     }
     * }
     * }
     * </pre>
     * 
     * @param name The name parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return used in internal operations, should be generated but not exported.
     */
    @Metadata(generated = true)
    Response<OuterModel> operationWithResponse(String name, RequestOptions requestOptions) {
        return this.instrumentation.instrumentWithResponse(
            "_Specs_.Azure.ClientGenerator.Core.Access.RelativeModelInOperation.operation", requestOptions,
            updatedOptions -> this.serviceClient.operationWithResponse(name, updatedOptions));
    }

    /**
     * Expected query parameter: kind="real"
     * Expected response body:
     * ```json
     * {
     * "name": "Madge",
     * "kind": "real"
     * }
     * ```.
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     kind: String (Required)
     *     name: String (Required)
     * }
     * }
     * </pre>
     * 
     * @param kind The kind parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return used in internal operations, should be generated but not exported.
     */
    @Metadata(generated = true)
    Response<AbstractModel> discriminatorWithResponse(String kind, RequestOptions requestOptions) {
        return this.instrumentation.instrumentWithResponse(
            "_Specs_.Azure.ClientGenerator.Core.Access.RelativeModelInOperation.discriminator", requestOptions,
            updatedOptions -> this.serviceClient.discriminatorWithResponse(kind, updatedOptions));
    }

    /**
     * Expected query parameter: name="Madge"
     * Expected response body:
     * ```json
     * {
     * "name": "Madge",
     * "inner":
     * {
     * "name": "Madge"
     * }
     * }
     * ```.
     * 
     * @param name The name parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return used in internal operations, should be generated but not exported.
     */
    @Metadata(generated = true)
    OuterModel operation(String name) {
        // Generated convenience method for operationWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return operationWithResponse(name, requestOptions).getValue();
    }

    /**
     * Expected query parameter: kind="real"
     * Expected response body:
     * ```json
     * {
     * "name": "Madge",
     * "kind": "real"
     * }
     * ```.
     * 
     * @param kind The kind parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return used in internal operations, should be generated but not exported.
     */
    @Metadata(generated = true)
    AbstractModel discriminator(String kind) {
        // Generated convenience method for discriminatorWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return discriminatorWithResponse(kind, requestOptions).getValue();
    }
}
