// Code generated by Microsoft (R) TypeSpec Code Generator.

package azure.clientgenerator.core.access;

import azure.clientgenerator.core.access.implementation.SharedModelInOperationsImpl;
import azure.clientgenerator.core.access.sharedmodelinoperation.models.SharedModel;
import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.ServiceClient;
import io.clientcore.core.http.exceptions.HttpResponseException;
import io.clientcore.core.http.models.RequestOptions;
import io.clientcore.core.http.models.Response;
import io.clientcore.core.instrumentation.Instrumentation;

/**
 * Initializes a new instance of the synchronous AccessClient type.
 */
@ServiceClient(builder = AccessClientBuilder.class)
public final class SharedModelInOperationClient {
    @Metadata(generated = true)
    private final SharedModelInOperationsImpl serviceClient;

    private final Instrumentation instrumentation;

    /**
     * Initializes an instance of SharedModelInOperationClient class.
     * 
     * @param serviceClient the service client implementation.
     * @param instrumentation the instrumentation instance.
     */
    @Metadata(generated = true)
    SharedModelInOperationClient(SharedModelInOperationsImpl serviceClient, Instrumentation instrumentation) {
        this.serviceClient = serviceClient;
        this.instrumentation = instrumentation;
    }

    /**
     * The publicMethod operation.
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     name: String (Required)
     * }
     * }
     * </pre>
     * 
     * @param name The name parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return used by both public and internal operation.
     */
    @Metadata(generated = true)
    public Response<SharedModel> publicMethodWithResponse(String name, RequestOptions requestOptions) {
        return this.instrumentation.instrumentWithResponse(
            "_Specs_.Azure.ClientGenerator.Core.Access.SharedModelInOperation.public", requestOptions,
            updatedOptions -> this.serviceClient.publicMethodWithResponse(name, updatedOptions));
    }

    /**
     * The internal operation.
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     name: String (Required)
     * }
     * }
     * </pre>
     * 
     * @param name The name parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return used by both public and internal operation.
     */
    @Metadata(generated = true)
    Response<SharedModel> internalWithResponse(String name, RequestOptions requestOptions) {
        return this.instrumentation.instrumentWithResponse(
            "_Specs_.Azure.ClientGenerator.Core.Access.SharedModelInOperation.internal", requestOptions,
            updatedOptions -> this.serviceClient.internalWithResponse(name, updatedOptions));
    }

    /**
     * The publicMethod operation.
     * 
     * @param name The name parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return used by both public and internal operation.
     */
    @Metadata(generated = true)
    public SharedModel publicMethod(String name) {
        // Generated convenience method for publicMethodWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return publicMethodWithResponse(name, requestOptions).getValue();
    }

    /**
     * The internal operation.
     * 
     * @param name The name parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return used by both public and internal operation.
     */
    @Metadata(generated = true)
    SharedModel internal(String name) {
        // Generated convenience method for internalWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return internalWithResponse(name, requestOptions).getValue();
    }
}
