// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the classes for Repeatability.
 * Illustrates OASIS repeatability headers.
 * <!-- end generated doc -->
 */
package specialheaders.repeatability;
