// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the implementations for NotVersioned.
 * Illustrates not-versioned server.
 * <!-- end generated doc -->
 */
package server.versions.notversioned.implementation;
